// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGXBqjyc_tEZanKJc4Zneoq8eg4-AF8KQ',
    appId: '1:733315032485:web:7f7d23eaa70e009f41b44c',
    messagingSenderId: '733315032485',
    projectId: 'pocket--path',
    authDomain: 'pocket--path.firebaseapp.com',
    storageBucket: 'pocket--path.appspot.com',
    measurementId: 'G-48GR6DLH4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCKzB1tIJQvb3Xhh-ss9Psqbn5-5kO2RI',
    appId: '1:733315032485:android:76e0957820c05a5d41b44c',
    messagingSenderId: '733315032485',
    projectId: 'pocket--path',
    storageBucket: 'pocket--path.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZyQmGRKfurt0TLNncX6koPiyNLHSBgjA',
    appId: '1:733315032485:ios:d6ad049cd27cab2341b44c',
    messagingSenderId: '733315032485',
    projectId: 'pocket--path',
    storageBucket: 'pocket--path.appspot.com',
    iosBundleId: 'com.example.costManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZyQmGRKfurt0TLNncX6koPiyNLHSBgjA',
    appId: '1:733315032485:ios:d6ad049cd27cab2341b44c',
    messagingSenderId: '733315032485',
    projectId: 'pocket--path',
    storageBucket: 'pocket--path.appspot.com',
    iosBundleId: 'com.example.costManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGXBqjyc_tEZanKJc4Zneoq8eg4-AF8KQ',
    appId: '1:733315032485:web:04adfb3fee090eef41b44c',
    messagingSenderId: '733315032485',
    projectId: 'pocket--path',
    authDomain: 'pocket--path.firebaseapp.com',
    storageBucket: 'pocket--path.appspot.com',
    measurementId: 'G-HBC5T11MDX',
  );
}
